language: ruby
env:
  - DOMAIN=.example.com APP_MAILER_FROM=me@example.com APP_MAILER_RETURN_PATH=me@example.com 
gemfile:
  - gemfiles/Gemfile.rails-head
matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-head
  include:
    - gemfile: Gemfile
      rvm: 2.2.2
services:
  - mongodb
rvm:
  - 2.2.2
  - ruby-head
script: bundle exec rspec
